spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
# Esta línea es la clave para que espere a que la tabla exista:
spring.jpa.defer-datasource-initialization=true