server:
  port: 8081

spring:
  application:
    name: chamoMarket

  datasource:
    url: jdbc:h2:file:./data/chamoMarket
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  h2:
    console:
      enabled: true

 feature/module3

  sql:
    init:
      mode: always


develop
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
 feature/module3

    defer-datasource-initialization: true
 develop
    properties:
      hibernate:
        format-sql: true

 feature/module3

develop
logging:
  level:
    org.springframework: INFO
    com.myapp: DEBUG