server:
  port: ${PORT:8080}

spring:
  application:
    name: chamoMarket
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    org.springframework: WARN

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 240000

frontend:
  url: ${FRONTEND_URL}
